// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmWCA_dZZqCBxZen0wplnfRp_miQ80Q4I',
    appId: '1:837248006182:android:b6e1ec2c05549a5a698ee7',
    messagingSenderId: '837248006182',
    projectId: 'theta-434b4',
    storageBucket: 'theta-434b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWqJ6Ws9JdCwF_KaA7FO9uKDCX1Tjb7Iw',
    appId: '1:837248006182:ios:6d2ff17e97de8c28698ee7',
    messagingSenderId: '837248006182',
    projectId: 'theta-434b4',
    storageBucket: 'theta-434b4.appspot.com',
    androidClientId: '837248006182-m37v5i43lsnq91mi65mvlkcvf3s53maa.apps.googleusercontent.com',
    iosClientId: '837248006182-a09m3fvrd9semr9oluhinf2caedc8ken.apps.googleusercontent.com',
    iosBundleId: 'com.codingwitht.loginFlutterApp',
  );

}